ENT.Type = "anim"
ENT.Base = "base_gmodentity"
ENT.PrintName = "弹药基类"
ENT.Spawnable = false
ENT.AmmoCount = 10
ENT.AmmoType = "9x19 mm Parabellum" -- 9.19mm parabelum
ENT.Model = "models/props_lab/box01a.mdl"
ENT.ModelScale = 1
ENT.IsZPickup = true